import { createReverseMap } from '@shared/utils'

export const RequestTypes = {
  LOGIN: 0,
  PING: 1,
  COMMAND: 2,
  REQUEST_PLAYER: 3,
  REQUEST_BOUNCE: 4,
  REQUEST_MATCH: 5,
  CONFIRM: 6,
  REQUEST_SCOREBOARD: 7
} as const

export type RequestType = (typeof RequestTypes)[keyof typeof RequestTypes]

/**
 * Event is basically the response type.
 * In the docs, it's always called as event, event id or event type.
 * To be coherent, I'll use "EventType" for the naming too.
 */
export const EventTypes = {
  SERVER_STARTUP: 0,
  SERVER_SHUTDOWN: 1,
  LOBBY_CONNECT: 2,
  LOBBY_DISCONNECT: 3,
  PLAYER_CONNECT: 4,
  PLAYER_SPAWN: 5,
  PLAYER_DEATH: 6,
  PLAYER_DISCONNECT: 7,
  PLAYER_TEAM_CHANGE: 8,
  PLAYER_LEVEL_UP: 9,
  PLAYER_GET_POWERUP: 10,
  PLAYER_DAMAGE: 11,
  PLAYER_LOADED: 12,
  TDM_ROUND_START: 13,
  TDM_ROUND_END: 14,
  TDM_FLAG_UNLOCKED: 15,
  TDM_SWITCH_SIDES: 16,
  CTF_TAKEN: 17,
  CTF_DROPPED: 18,
  CTF_RETURNED: 19,
  CTF_SCORED: 20,
  CTF_GENERATOR_REPAIRED: 21,
  CTF_GENERATOR_DESTROYED: 22,
  CTF_TURRET_REPAIRED: 23,
  CTF_TURRET_DESTROYED: 24,
  CTF_RESUPPLY_REPAIRED: 25,
  CTF_RESUPPLY_DESTROYED: 26,
  MATCH_END: 27,
  MATCH_OVERTIME: 28,
  MATCH_START: 29,
  SURVIVAL_NEW_WAVE: 30,
  SURVIVAL_WAVE_BEGINS: 31,
  SURVIVAL_BUY_CHEST: 32,
  LOG_MESSAGE: 33,
  REQUEST_DATA: 34,
  COMMAND_ENTERED: 35,
  RCON_LOGGED_IN: 36,
  MATCH_PAUSED: 37,
  MATCH_UNPAUSED: 38,
  WARMUP_START: 39,
  RCON_DISCONNECT: 40,
  RCON_PING: 41,
  CHAT_MESSAGE: 42,
  SURVIVAL_GET_VICE: 43,
  SURVIVAL_USE_VICE: 44,
  SURVIVAL_PLAYER_REVIVE: 45,
  PLAYER_TAUNT: 46,
  SURVIVAL_COMPLETE_MISSION: 47,
  SURVIVAL_TAKE_MISSION: 48,
  SURVIVAL_FAIL_MISSION: 49,
  ZOMBRAINS_REVIVE: 50,
  ZOMBRAINS_BUY_WEAPON: 51,
  ZOMBRAINS_BEGIN: 52,
  ZOMBRAINS_HELICOPTER_ARRIVING: 53,
  ZOMBRAINS_HELICOPTER_BOARDING: 54,
  ZOMBRAINS_HELICOPTER_PLAYER_BOARDED: 55,
  ZOMBRAINS_END: 56,
  GAME_OVER: 57,
  SERVER_EMPTY: 58,
  WEAPONSDEAL_RANKCHANGE: 59,
  TAKEOVER_FLAGCAPTURE: 60,
  TAKEOVER_FLAGSCREATED: 61,
  PLAYER_LOADOUT: 62,
  SURVIVAL_BOMB_DEFUSED: 63,
  SURVIVAL_BOMB_EXPLODED: 64,
  SURVIVAL_BOMB_REARMED: 65,
  SLEEP: 66,
  WAKE: 67
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]

export const RequestTypeNames = createReverseMap(RequestTypes)
export const EventTypeNames = createReverseMap(EventTypes)
