import { createReverseMap } from '@shared/utils'

export const Vices = {
  LAGER: 0,
  CIDER: 1,
  ALE: 2,
  MOONSHINE: 3,
  RED_WINE: 4,
  WHISKEY: 5,
  MARTINI: 6,
  JAGERBOMB: 7,
  TEQUILA: 8,
  JOINT: 9,
  STOUT: 10,
  MARGARITA: 11,
  GIN_TONIC: 12,
  BLOODY_MARY: 13,
  SCREWDRIVER: 14,
  SAKE: 15,
  MEAD: 16,
  WHITE_WINE: 17,
  CIGAR: 18,
  VARIAN_CIGAR: 19,
  PORTER: 20,
  ENERGY_DRINK: 21,
  PAINKILLERS: 22,
  MOJITO: 23,
  BOURBON_COLA: 24,
  BEER: 25,
  SPLIFF: 26,
  STIMULANTS: 27,
  ABSINTHE: 28,
  RUM: 29,
  CHAMPAGNE: 30,
  VAPE_PEN: 31,
  SHERRY: 32,
  ESPRESSO: 33,
  WATER: 34,
  RUBBING_ALCOHOL: 35,
  HOT_WINGS: 36,
  ANTACIDS: 37,
  SMOKES: 38,
  VODKA: 39,
  MARIA: 40,
  SUPER_ANTACIDS: 41,
  INDIGOS_RESERVE: 42
} as const

export const ViceNames = createReverseMap(Vices)

export type Vice = (typeof Vices)[keyof typeof Vices]
